import assert from 'node:assert/strict';
import fs from 'node:fs';
import {searchProjects,latestProject} from '../src/matcher.js';
import {fallbackConcept,validConcept} from '../src/builder.js';
import {parseTerminal} from '../src/terminal.js';
import worker,{ideaEndpoint} from '../dist/server/index.js';
const ps=JSON.parse(fs.readFileSync('src/projects.json'));let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS '+name)};
test('Mobile search finds all four app entries',()=>assert.equal(searchProjects('Show me your mobile apps',ps).projects.length,4));
test('Logistics search matches both Trackora entries',()=>assert.deepEqual(searchProjects('Show me logistics projects',ps).projects.map(p=>p.name),['Trackora','Trackora']));
test('AI search only returns represented AI capability',()=>assert.deepEqual(searchProjects('What have you built with AI?',ps).projects.map(p=>p.name),['DM-ERP']));
test('Booking search returns genuinely matching capabilities',()=>{const r=searchProjects('Show me booking platforms',ps).projects;assert(r.some(p=>p.name==='PinevilleLeb'));assert(r.some(p=>p.name==='Assia Padel'));assert(!r.some(p=>p.name==='Trackora'))});
test('Newest does not invent launch dates',()=>{assert.equal(latestProject(ps),null);assert.equal(searchProjects('Show me newest projects',ps).projects.length,0)});
test('No-match e-commerce request does not invent prior work',()=>assert.equal(searchProjects('I need an e-commerce website',ps).projects.length,0));
test('Fallback preserves the visitor’s idea and only references existing IDs',()=>{const idea='<script>alert(1)</script> boat booking';const c=fallbackConcept('Booking Platform',idea,ps);assert.equal(c.summary,idea);assert(validConcept(c,ps));assert.equal(c.complexity,null)});
test('Validator rejects invented IDs, unsafe types and impossible complexity',()=>{const c=fallbackConcept('Website','A new portfolio',ps);assert(!validConcept({...c,matchingProjectIds:['invented']},ps));assert(!validConcept({...c,coreSystems:[{}]},ps));assert(!validConcept({...c,complexity:{score:100,level:'high',explanation:''}},ps))});
test('Terminal handles required commands without execution',()=>{for(const cmd of ['help','projects','apps','about','skills','latest','contact','random','clear','exit','sudo hire alain','coffee','rm -rf /'])assert(Array.isArray(parseTerminal(cmd,ps).lines));assert.equal(parseTerminal('rm -rf /',ps).lines[0],'ACCESS DENIED — Private development environment.');assert.equal(parseTerminal('eval alert(1)',ps).lines[0],'ACCESS DENIED — Private development environment.');assert.equal(parseTerminal('open website-destinotel',ps).project.name,'Destinotel');assert(parseTerminal('open unknown',ps).lines[0].includes('Unknown'))});
const page=fs.readFileSync('dist/index.html','utf8');
test('All 13 cards and descriptions are server-rendered and crawlable',()=>{assert.equal((page.match(/data-project-id=/g)||[]).length,13);assert.equal((page.match(/class="project-description"/g)||[]).length,13);for(const p of ps){assert(page.includes('project-'+p.id));if(p.url)assert(page.includes(p.url))}});
test('No public repository links, fake progress or moving stripe elements',()=>{assert(!/github\.com|github\.io/i.test(page));assert(!/moving-light|neon-stripe/.test(page+fs.readFileSync('dist/os.js','utf8')))});
test('Asset references exist',()=>{for(const m of page.matchAll(/(?:src|href)="([^"#]+)"/g)){const p=m[1];if(!/^(https?:|data:)/.test(p))assert(fs.existsSync('dist/'+p),p)}});
for(const path of ['/','/os.js','/projects.json','/assets/parently.png']){const r=await worker.fetch(new Request('https://www.dev-mania.com'+path),{});assert.equal(r.status,200);assert((await r.arrayBuffer()).byteLength>0);checks++}
assert.equal((await worker.fetch(new Request('https://www.dev-mania.com/server/index.js'),{})).status,404);checks++;
const req=(body,headers={})=>new Request('https://www.dev-mania.com/api/idea',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
assert.equal((await ideaEndpoint(req({productType:'Website',idea:'A portfolio for my business'}),{})).status,503);checks++;
assert.equal((await ideaEndpoint(req({productType:'Website',idea:'abc'}),{})).status,400);checks++;
assert.equal((await ideaEndpoint(req({productType:'Website',idea:'A portfolio for my business'},{Origin:'https://evil.example'}),{})).status,403);checks++;
const originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({output:[{content:[{type:'output_text',text:JSON.stringify(fallbackConcept('Website','My business website',ps))}]}]}));
const ai=await ideaEndpoint(req({productType:'Website',idea:'A portfolio for my business'},{'CF-Connecting-IP':'test-ai'}),{OPENAI_API_KEY:'test',OPENAI_MODEL:'test'});assert.equal(ai.status,200);assert(validConcept(await ai.json(),ps));checks++;
globalThis.fetch=async()=>new Response(JSON.stringify({output:[{content:[{type:'output_text',text:'{"projectName":"bad"}'}]}]}));assert.equal((await ideaEndpoint(req({productType:'Website',idea:'A portfolio for my business'},{'CF-Connecting-IP':'test-invalid'}),{OPENAI_API_KEY:'test',OPENAI_MODEL:'test'})).status,502);checks++;globalThis.fetch=originalFetch;
for(let i=0;i<5;i++)await ideaEndpoint(req({productType:'Website',idea:'A portfolio for my business'},{'CF-Connecting-IP':'rate-test'}),{});assert.equal((await ideaEndpoint(req({productType:'Website',idea:'A portfolio for my business'},{'CF-Connecting-IP':'rate-test'}),{})).status,429);checks++;
console.log(`${checks} checks passed.`);
