import {buildGrowth,toolPaths} from './growth.mjs';
import fs from 'node:fs';
import {services} from './services.mjs';
import {googleTag} from './analytics.mjs';
export const posts=JSON.parse(fs.readFileSync('src/blog/posts.json','utf8'));
const origin='https://www.dev-mania.com';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const url=p=>'/blog/'+p.slug+'/';
const categories=[...new Set(posts.map(p=>p.category))];
const jsonld=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const org={'@type':'Organization',name:'DevMania',url:origin+'/',logo:origin+'/assets/logo.png'};
const card=p=>`<article class="journal-card"><span class="journal-category">${esc(p.category)}</span><h2><a href="${url(p)}">${esc(p.title)}</a></h2><p>${esc(p.description)}</p><span class="journal-meta">${minutes(p)} min read <span aria-hidden="true">↗</span></span></article>`;
const minutes=p=>Math.max(1,Math.ceil(p.sections.map(s=>s.text).join(' ').split(/\s+/).length/200));
function page(title,description,path,content,schema,type='website') {return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050505"><title>${esc(title)} | DevMania</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin+path}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin+path}"><meta property="og:site_name" content="DevMania"><meta property="og:image" content="${origin}/assets/hero-build.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${origin}/assets/hero-build.png"><link rel="alternate" type="application/rss+xml" title="DevMania Journal" href="/feed.xml"><meta name="robots" content="max-image-preview:large"><script src="/engagement.js" defer></script><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/blog.css"><script type="application/ld+json">${jsonld(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a><header class="journal-header"><a class="journal-brand" href="/">Dev<span>Mania</span><small>IDEAS INTO DIGITAL REALITY</small></a><nav aria-label="Main navigation"><a href="/#work">Work</a><a href="/tools/">Free tools</a><a href="/blog/" aria-current="${path==='/blog/'?'page':'false'}">Blog</a><a href="/#contact">Let’s talk ↗</a></nav></header><main id="main">${content}</main><footer class="journal-footer"><a class="journal-brand" href="/">Dev<span>Mania</span></a><p>Practical thinking for your next digital product.</p><nav aria-label="Footer"><a href="/tools/">Free tools</a><a href="/feed.xml">RSS feed</a><a href="/blog/">All articles</a><a href="/#about">About DevMania</a><a href="/#contact">Discuss a project</a></nav><small>© 2026 DevMania</small></footer></body></html>`;}
const breadcrumbs=(items)=>({'@type':'BreadcrumbList',itemListElement:items.map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:origin+path}))});
const crumbs=(items)=>`<nav class="breadcrumbs" aria-label="Breadcrumb">${items.map(([name,path],i)=>i===items.length-1?`<span aria-current="page">${esc(name)}</span>`:`<a href="${path}">${esc(name)}</a><span aria-hidden="true">/</span>`).join('')}</nav>`;
export function buildBlog(){
 fs.mkdirSync('dist/blog',{recursive:true});fs.copyFileSync('src/blog/blog.css','dist/blog.css');
 const files=['blog.css'];
 function write(path,html){const file=path+'index.html';fs.mkdirSync('dist/'+path,{recursive:true});fs.writeFileSync('dist/'+file,html.replace('</head>',googleTag+'</head>'));files.push(file);}
 files.push(...buildGrowth(page,write));
 for(const service of services){
  const path='/services/'+service.slug+'/';
  const items=[['Home','/'],[service.heading,path]];
  const sections=service.sections.map(([heading,body],i)=>`<section id="step-${i+1}"><h2>${esc(heading)}</h2><p>${esc(body)}</p></section>`).join('');
  const links=(items)=>items.map(([label,href])=>`<li><a href="${href}">${esc(label)} ↗</a></li>`).join('');
  const content=`${crumbs(items)}<article class="service-page"><header class="article-header"><span class="journal-eyebrow">DEVMANIA / SERVICES</span><h1>${esc(service.heading)}</h1><p class="article-deck">${esc(service.intro)}</p></header><div class="article-layout"><aside class="article-toc"><nav aria-label="On this page"><h2>What to consider</h2>${service.sections.map(([heading],i)=>`<a href="#step-${i+1}">${esc(heading)}</a>`).join('')}</nav></aside><div class="article-body">${sections}<section class="service-links"><h2>Explore related work</h2><ul>${links(service.examples)}</ul><h2>Free planning tools</h2><ul><li><a href="/tools/website-brief-builder/">Create a website brief</a></li><li><a href="/tools/website-launch-checklist/">Website launch checklist</a></li></ul><h2>Planning guides</h2><ul>${links(service.guides)}</ul></section><aside class="article-cta"><span class="journal-eyebrow">START A CONVERSATION</span><h2>Tell us what you want to build.</h2><p>Share the audience, your goal and the systems involved. We can start with the smallest useful scope.</p><a href="/#contact">Discuss your project ↗</a></aside></div></div></article>`;
  const schema={'@context':'https://schema.org','@graph':[{'@type':'Service',name:service.heading,description:service.description,url:origin+path,provider:org,areaServed:{'@type':'Place',name:'Dubai, United Arab Emirates'}},breadcrumbs(items)]};
  write(path.slice(1),page(service.title,service.description,path,content,schema));
 }
 const categoryLinks=`<nav class="journal-topics" aria-label="Blog topics"><a href="/blog/">All topics <span>25</span></a>${categories.map(c=>`<a href="/blog/topics/${slug(c)}/">${esc(c)} <span>${posts.filter(p=>p.category===c).length}</span></a>`).join('')}</nav>`;
 write('blog/',page('Web Development, Apps & AI Blog','Practical guides to websites, mobile apps, API integration, ChatGPT, Claude and AI for business owners planning their next digital product.','/blog/',`<section class="journal-hero"><span class="journal-eyebrow">THE DEVMANIA JOURNAL / 25 GUIDES</span><h1>Better questions.<br><em>Better digital products.</em></h1><p>From the first website brief to a useful AI workflow. Practical guides for people turning ideas into something real.</p></section>${categoryLinks}<aside class="tool-promo"><strong>Put the guides to work.</strong> <a href="/tools/website-brief-builder/">Create a free website brief</a> or <a href="/tools/website-launch-checklist/">check your launch plan</a>. No sign-up required.</aside><section class="journal-grid" aria-label="All articles">${posts.map(card).join('')}</section><aside class="journal-note"><h2>About these guides</h2><p>Published by DevMania. These guides were created with AI assistance and focus on practical planning. Examples are illustrative, not client case studies. Provider features and pricing can change; consult linked official documentation before implementation.</p><a href="/#about">Meet the developer behind DevMania ↗</a></aside>`,{'@context':'https://schema.org','@type':'Blog',name:'DevMania Journal',url:origin+'/blog/',publisher:org,blogPost:posts.map(p=>({'@type':'BlogPosting',headline:p.title,url:origin+url(p)}))}));
 for(const c of categories){const path='/blog/topics/'+slug(c)+'/';const ps=posts.filter(p=>p.category===c);write(path.slice(1),page(c+' Guides',`Explore ${ps.length} practical ${c} guides from DevMania, with examples and next steps for planning digital products.`,path,`${crumbs([['Home','/'],['Blog','/blog/'],[c,path]])}<section class="journal-hero"><span class="journal-eyebrow">${ps.length} PRACTICAL GUIDES</span><h1>${esc(c)}<em> explained.</em></h1><p>Clear decisions, useful examples and a next step you can act on.</p></section>${categoryLinks}<section class="journal-grid">${ps.map(card).join('')}</section>`,{'@context':'https://schema.org','@type':'CollectionPage',name:c+' Guides',url:origin+path}));}
 for(const p of posts){const path=url(p),topic='/blog/topics/'+slug(p.category)+'/';const items=[['Home','/'],['Blog','/blog/'],[p.category,topic],[p.title,path]];const related=posts.filter(x=>x!==p&&x.category===p.category).slice(0,3);
 const suggested=p.category==='Web Development'?'website-development':p.category==='App Development'?'mobile-app-development':p.category==='API Integration'?'api-integration':'ai-business-solutions';
 const shareUrl=encodeURIComponent(origin+path);
 const body=`${crumbs(items)}<article><header class="article-header"><a class="journal-eyebrow" href="${topic}">${esc(p.category)}</a><h1>${esc(p.title)}</h1><p class="article-deck">${esc(p.description)}</p><div class="journal-meta">By <a href="/#about">DevMania</a> · <time datetime="${p.date}">21 September 2026</time> · ${minutes(p)} min read</div></header><div class="share-links" aria-label="Share this guide"><a data-share="linkedin" href="https://www.linkedin.com/sharing/share-offsite/?url=${shareUrl}" target="_blank" rel="noopener noreferrer">Share on LinkedIn</a><a data-share="whatsapp" href="https://api.whatsapp.com/send?text=${encodeURIComponent(p.title+' '+origin+path)}" target="_blank" rel="noopener noreferrer">Share on WhatsApp</a></div><div class="article-layout"><aside class="article-toc"><nav aria-label="In this article"><h2>In this guide</h2>${p.sections.map((s,i)=>`<a href="#section-${i+1}">${esc(s.heading)}</a>`).join('')}</nav></aside><div class="article-body">${p.sections.map((s,i)=>`<section id="section-${i+1}"><h2>${esc(s.heading)}</h2><p>${esc(s.text)}</p></section>`).join('')}${p.sources.length?`<section class="article-sources"><h2>Official references</h2><ul>${p.sources.map(([label,link])=>`<li><a href="${esc(link)}" rel="noopener noreferrer">${esc(label)} ↗</a></li>`).join('')}</ul></section>`:''}<aside class="tool-promo"><strong>Turn planning into action.</strong> <a href="/tools/website-brief-builder/">Create an editable website brief</a> or <a href="/tools/website-launch-checklist/">work through the launch checklist</a>.</aside><p class="editorial-note">Published by DevMania with AI assistance. Examples illustrate planning approaches and do not claim client results. Check current provider documentation before implementing product-specific features.</p><aside class="article-cta"><span class="journal-eyebrow">FROM READING TO BUILDING</span><h2>Put your idea into practice.</h2><p>Explore DevMania’s work or tell us what you want your next website, app or integration to do.</p><a href="/services/${suggested}/">Explore ${esc(services.find(s=>s.slug===suggested).heading)} ↗</a><a href="/#contact">Discuss your project</a></aside></div></div></article><section class="related"><span class="journal-eyebrow">KEEP EXPLORING</span><h2>Related guides</h2><div class="journal-grid">${related.map(card).join('')}</div></section>`;
 write(path.slice(1),page(p.title,p.description,path,body,{'@context':'https://schema.org','@graph':[{'@type':'BlogPosting',headline:p.title,description:p.description,datePublished:p.date,dateModified:p.date,mainEntityOfPage:origin+path,url:origin+path,author:org,publisher:org,image:origin+'/assets/hero-build.png',articleSection:p.category,inLanguage:'en',wordCount:p.sections.map(s=>s.text).join(' ').split(/\s+/).length},breadcrumbs(items)]},'article'));
 }
 const urls=['/',...toolPaths,...services.map(s=>'/services/'+s.slug+'/'),'/blog/',...categories.map(c=>'/blog/topics/'+slug(c)+'/'),...posts.map(url)];
 fs.writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(path=>`<url><loc>${origin+path}</loc></url>`).join('')+'</urlset>\n');
 fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /server/\nDisallow: /.openai/\nSitemap: ${origin}/sitemap.xml\n`);
 const xmlEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 fs.writeFileSync('dist/feed.xml','<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>DevMania Journal</title><link>'+origin+'/blog/</link><description>Practical guides to websites, apps and AI workflows.</description><language>en</language>'+posts.map(p=>'<item><title>'+xmlEscape(p.title)+'</title><link>'+origin+url(p)+'</link><guid>'+origin+url(p)+'</guid><description>'+xmlEscape(p.description)+'</description></item>').join('')+'</channel></rss>');
 files.push('sitemap.xml','robots.txt','feed.xml');
 console.log(`Built ${posts.length} articles and ${categories.length} topic pages.`);return files;
}
