import fs from 'node:fs';
export const posts=JSON.parse(fs.readFileSync('src/blog/posts.json','utf8'));
const origin='https://www.dev-mania.com';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const url=p=>'/blog/'+p.slug+'/';
const categories=[...new Set(posts.map(p=>p.category))];
const jsonld=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const org={'@type':'Organization',name:'DevMania',url:origin+'/',logo:origin+'/assets/logo.png'};
const card=p=>`<article class="journal-card"><span class="journal-category">${esc(p.category)}</span><h2><a href="${url(p)}">${esc(p.title)}</a></h2><p>${esc(p.description)}</p><span class="journal-meta">${minutes(p)} min read <span aria-hidden="true">↗</span></span></article>`;
const minutes=p=>Math.max(1,Math.ceil(p.sections.map(s=>s.text).join(' ').split(/\s+/).length/200));
function page(title,description,path,content,schema,type='website') {return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050505"><title>${esc(title)} | DevMania</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin+path}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin+path}"><meta property="og:site_name" content="DevMania"><meta property="og:image" content="${origin}/assets/hero-build.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${origin}/assets/hero-build.png"><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/blog.css"><script type="application/ld+json">${jsonld(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a><header class="journal-header"><a class="journal-brand" href="/">Dev<span>Mania</span><small>IDEAS INTO DIGITAL REALITY</small></a><nav aria-label="Main navigation"><a href="/#work">Work</a><a href="/blog/" aria-current="${path==='/blog/'?'page':'false'}">Blog</a><a href="/#contact">Let’s talk ↗</a></nav></header><main id="main">${content}</main><footer class="journal-footer"><a class="journal-brand" href="/">Dev<span>Mania</span></a><p>Practical thinking for your next digital product.</p><nav aria-label="Footer"><a href="/blog/">All articles</a><a href="/#about">About DevMania</a><a href="/#contact">Discuss a project</a></nav><small>© 2026 DevMania</small></footer></body></html>`;}
const breadcrumbs=(items)=>({'@type':'BreadcrumbList',itemListElement:items.map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:origin+path}))});
const crumbs=(items)=>`<nav class="breadcrumbs" aria-label="Breadcrumb">${items.map(([name,path],i)=>i===items.length-1?`<span aria-current="page">${esc(name)}</span>`:`<a href="${path}">${esc(name)}</a><span aria-hidden="true">/</span>`).join('')}</nav>`;
export function buildBlog(){
 fs.mkdirSync('dist/blog',{recursive:true});fs.copyFileSync('src/blog/blog.css','dist/blog.css');
 const files=['blog.css'];
 function write(path,html){const file=path+'index.html';fs.mkdirSync('dist/'+path,{recursive:true});fs.writeFileSync('dist/'+file,html);files.push(file);}
 const categoryLinks=`<nav class="journal-topics" aria-label="Blog topics"><a href="/blog/">All topics <span>25</span></a>${categories.map(c=>`<a href="/blog/topics/${slug(c)}/">${esc(c)} <span>${posts.filter(p=>p.category===c).length}</span></a>`).join('')}</nav>`;
 write('blog/',page('Web Development, Apps & AI Blog','Practical guides to websites, mobile apps, API integration, ChatGPT, Claude and AI for business owners planning their next digital product.','/blog/',`<section class="journal-hero"><span class="journal-eyebrow">THE DEVMANIA JOURNAL / 25 GUIDES</span><h1>Better questions.<br><em>Better digital products.</em></h1><p>From the first website brief to a useful AI workflow. Practical guides for people turning ideas into something real.</p></section>${categoryLinks}<section class="journal-grid" aria-label="All articles">${posts.map(card).join('')}</section><aside class="journal-note"><h2>About these guides</h2><p>Published by DevMania. These guides were created with AI assistance and focus on practical planning. Examples are illustrative, not client case studies. Provider features and pricing can change; consult linked official documentation before implementation.</p><a href="/#about">Meet the developer behind DevMania ↗</a></aside>`,{'@context':'https://schema.org','@type':'Blog',name:'DevMania Journal',url:origin+'/blog/',publisher:org,blogPost:posts.map(p=>({'@type':'BlogPosting',headline:p.title,url:origin+url(p)}))}));
 for(const c of categories){const path='/blog/topics/'+slug(c)+'/';const ps=posts.filter(p=>p.category===c);write(path.slice(1),page(c+' Guides',`Explore ${ps.length} practical ${c} guides from DevMania, with examples and next steps for planning digital products.`,path,`${crumbs([['Home','/'],['Blog','/blog/'],[c,path]])}<section class="journal-hero"><span class="journal-eyebrow">${ps.length} PRACTICAL GUIDES</span><h1>${esc(c)}<em> explained.</em></h1><p>Clear decisions, useful examples and a next step you can act on.</p></section>${categoryLinks}<section class="journal-grid">${ps.map(card).join('')}</section>`,{'@context':'https://schema.org','@type':'CollectionPage',name:c+' Guides',url:origin+path}));}
 for(const p of posts){const path=url(p),topic='/blog/topics/'+slug(p.category)+'/';const items=[['Home','/'],['Blog','/blog/'],[p.category,topic],[p.title,path]];const related=posts.filter(x=>x!==p&&x.category===p.category).slice(0,3);
 const body=`${crumbs(items)}<article><header class="article-header"><a class="journal-eyebrow" href="${topic}">${esc(p.category)}</a><h1>${esc(p.title)}</h1><p class="article-deck">${esc(p.description)}</p><div class="journal-meta">By <a href="/#about">DevMania</a> · <time datetime="${p.date}">21 September 2026</time> · ${minutes(p)} min read</div></header><div class="article-layout"><aside class="article-toc"><nav aria-label="In this article"><h2>In this guide</h2>${p.sections.map((s,i)=>`<a href="#section-${i+1}">${esc(s.heading)}</a>`).join('')}</nav></aside><div class="article-body">${p.sections.map((s,i)=>`<section id="section-${i+1}"><h2>${esc(s.heading)}</h2><p>${esc(s.text)}</p></section>`).join('')}${p.sources.length?`<section class="article-sources"><h2>Official references</h2><ul>${p.sources.map(([label,link])=>`<li><a href="${esc(link)}" rel="noopener noreferrer">${esc(label)} ↗</a></li>`).join('')}</ul></section>`:''}<p class="editorial-note">Published by DevMania with AI assistance. Examples illustrate planning approaches and do not claim client results. Check current provider documentation before implementing product-specific features.</p><aside class="article-cta"><span class="journal-eyebrow">FROM READING TO BUILDING</span><h2>Put your idea into practice.</h2><p>Explore DevMania’s work or tell us what you want your next website, app or integration to do.</p><a href="/#contact">Discuss your project ↗</a><a href="/#work">Explore the portfolio</a></aside></div></div></article><section class="related"><span class="journal-eyebrow">KEEP EXPLORING</span><h2>Related guides</h2><div class="journal-grid">${related.map(card).join('')}</div></section>`;
 write(path.slice(1),page(p.title,p.description,path,body,{'@context':'https://schema.org','@graph':[{'@type':'BlogPosting',headline:p.title,description:p.description,datePublished:p.date,dateModified:p.date,mainEntityOfPage:origin+path,url:origin+path,author:org,publisher:org,image:origin+'/assets/hero-build.png',articleSection:p.category,inLanguage:'en',wordCount:p.sections.map(s=>s.text).join(' ').split(/\s+/).length},breadcrumbs(items)]},'article'));
 }
 const urls=['/','/blog/',...categories.map(c=>'/blog/topics/'+slug(c)+'/'),...posts.map(url)];
 fs.writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(path=>`<url><loc>${origin+path}</loc></url>`).join('')+'</urlset>\n');
 fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /server/\nDisallow: /.openai/\nSitemap: ${origin}/sitemap.xml\n`);
 files.push('sitemap.xml','robots.txt');
 console.log(`Built ${posts.length} articles and ${categories.length} topic pages.`);return files;
}
