import fs from 'node:fs';
const projects=JSON.parse(fs.readFileSync('src/projects.json','utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(p){const image=p.image?`<img class="${esc(p.imageClass)}" src="${esc(p.image)}" alt="${esc(p.imageAlt)}" loading="lazy">`:'';return `<${p.url?'a':'article'} class="work-card" id="project-${p.id}" data-project-id="${p.id}" ${p.url?`href="${esc(p.url)}" target="_blank" rel="noopener noreferrer"`:''}><div class="work-thumbnail" data-project="${p.legacyKey}">${p.id==='app-parently'?`<div class="parently-icon-frame">${image}</div>`:image}<span class="thumbnail-kind">${p.categories[0]==='Apps'?'APP':p.categories[0]==='Websites'?'WEBSITE':'SOFTWARE'}</span><span class="thumbnail-name">${esc(p.name)}</span><span class="thumbnail-rule" aria-hidden="true"></span></div><div class="work-card-caption"><h5>${esc(p.name)}</h5><span>${esc(p.caption)}</span></div><p class="project-description">${esc(p.shortDescription)}</p></${p.url?'a':'article'}>`}
let work='';for(const category of ['Apps','Websites','Softwares']){const subset=projects.filter(p=>p.categories.includes(category));work+=`<section class="work-category" aria-label="${category}"><div class="work-category-heading"><h3>${category}</h3><span>${subset.length} PROJECT${subset.length===1?'':'S'}</span></div>`;for(const status of ['live','building']){const ps=subset.filter(p=>p.status===status);if(!ps.length)continue;work+=`<div class="work-status-group"><div class="work-status-heading"><h4>${status==='live'?'Published':'In the Build'}</h4><span class="work-count">${ps.length}</span></div><div class="work-grid">${ps.map(card).join('')}</div></div>`}work+='</section>'}
const counts=[['Projects',projects.length],['Websites',projects.filter(p=>p.platforms.includes('web')).length],['Apps',projects.filter(p=>p.categories.includes('Apps')).length],['AI projects',projects.filter(p=>p.capabilities.includes('ai')).length]];
const status=`<section class="os-status section" aria-label="DevMania status"><div><span class="eyebrow">DEV//MANIA STATUS</span><p class="system-online">● SYSTEM ONLINE</p></div><div class="os-counts">${counts.map(([label,n])=>`<div><strong>${n}</strong><span>${label}</span></div>`).join('')}</div><p class="build-status">Currently building: ${projects.filter(p=>p.status==='building').map(p=>esc(p.name)).join(' · ')}</p></section>`;
const entry='<section class="section idea-entry"><div><span class="eyebrow">YOUR NEXT PRODUCT</span><h2>Have an idea?<br><em>Let’s give it shape.</em></h2><p>Explore the systems your product could need and discover related DevMania work.</p></div><button class="button" type="button" data-open-builder>Build my idea</button></section>';
let page=fs.readFileSync('src/index.template.html','utf8').replace('<!-- PROJECT_REGISTRY -->',work).replace('<!-- OS_STATUS -->',status).replace('<!-- IDEA_ENTRY -->',entry);
fs.writeFileSync('dist/index.html',page);fs.copyFileSync('src/projects.json','dist/projects.json');
for(const file of ['os.js','os.css','matcher.js','builder.js','terminal.js'])fs.copyFileSync('src/'+file,'dist/'+file);
console.log(`Built ${projects.length} project cards and interactive portfolio assets.`);
// Embed an explicit public-file allowlist in the Worker; no repository source is served.
const publicNames=['index.html','style.css','app.js','os.css','os.js','matcher.js','builder.js','terminal.js','projects.json'];
const files=[...publicNames,...fs.readdirSync('dist/assets').map(n=>'assets/'+n)];const assets={};
const types={html:'text/html; charset=utf-8',css:'text/css; charset=utf-8',js:'text/javascript; charset=utf-8',json:'application/json',png:'image/png',jpeg:'image/jpeg',jpg:'image/jpeg',svg:'image/svg+xml'};
for(const name of files){const ext=name.split('.').pop();const binary=['png','jpeg','jpg'].includes(ext);assets['/'+name]={type:types[ext]||'application/octet-stream',base64:binary,body:fs.readFileSync('dist/'+name,binary?'base64':'utf8')}}
fs.mkdirSync('dist/server',{recursive:true});fs.writeFileSync('dist/server/assets.js','export default '+JSON.stringify(assets)+';');fs.writeFileSync('dist/server/projects.js','export default '+JSON.stringify(projects)+';');fs.copyFileSync('server/worker.js','dist/server/index.js');
const validator=fs.readFileSync('src/builder.js','utf8').match(/export function validConcept[\s\S]*?\nexport function mountBuilder/)[0].replace(/\nexport function mountBuilder$/,'');fs.writeFileSync('dist/server/validation.js',validator);
fs.mkdirSync('dist/.openai',{recursive:true});fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');
