import {buildBlog} from './build-blog.mjs';
import fs from 'node:fs';
const projects=JSON.parse(fs.readFileSync('src/projects.json','utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(p){const image=p.image?`<img class="${esc(p.imageClass)}" src="${esc(p.image)}" alt="${esc(p.imageAlt)}" loading="lazy">`:'';return `<div class="exp-project-wrap"><${p.url?'a':'article'} class="work-card" id="project-${p.id}" data-project-id="${p.id}" ${p.url?`href="${esc(p.url)}" target="_blank" rel="noopener noreferrer"`:''}><div class="work-thumbnail" data-project="${p.legacyKey}">${p.id==='app-parently'?`<div class="parently-icon-frame">${image}</div>`:image}<span class="thumbnail-kind">${p.categories[0]==='Apps'?'APP':p.categories[0]==='Websites'?'WEBSITE':p.categories[0]==='SaaS'?'SaaS':'SOFTWARE'}</span><span class="thumbnail-name">${esc(p.name)}</span><span class="thumbnail-rule" aria-hidden="true"></span></div><div class="work-card-caption"><h5>${esc(p.name)}</h5><span>${esc(p.caption)}</span></div><p class="project-description">${esc(p.shortDescription)}</p></${p.url?'a':'article'}><div class="exp-project-tools"><button type="button" class="exp-button" data-project-action="project" data-project="${p.id}" aria-label="Explore ${esc(p.name)}">Explore</button>${p.experience?.xrayEnabled?`<button type="button" class="exp-button" data-project-action="xray" data-project="${p.id}" aria-label="X-Ray ${esc(p.name)}">X-Ray</button>`:''}${p.experience?.playground?.enabled?`<button type="button" class="exp-button" data-project-action="playground" data-project="${p.id}" aria-label="Try ${esc(p.name)}">Try it</button>`:''}</div></div>`}
let work='';for(const category of ['Apps','Websites',...new Set(projects.flatMap(p=>p.categories).filter(c=>!['Apps','Websites'].includes(c))) ]){const subset=projects.filter(p=>p.categories.includes(category));work+=`<section class="work-category" aria-label="${category}"><div class="work-category-heading"><h3>${category}</h3><span>${subset.length} PROJECT${subset.length===1?'':'S'}</span></div>`;for(const status of ['live','building']){const ps=subset.filter(p=>p.status===status);if(!ps.length)continue;work+=`<div class="work-status-group"><div class="work-status-heading"><h4>${status==='live'?'Published':'In the Build'}</h4><span class="work-count">${ps.length}</span></div><div class="work-grid">${ps.map(card).join('')}</div></div>`}work+='</section>'}
const counts=[['Projects',projects.length],['Websites',projects.filter(p=>p.platforms.includes('web')).length],['Apps',projects.filter(p=>p.categories.includes('Apps')).length],['AI projects',projects.filter(p=>p.capabilities.includes('ai')).length]];
const status=`<section class="os-status section" aria-label="DevMania status"><div><span class="eyebrow">DEV//MANIA STATUS</span><p class="system-online">● SYSTEM ONLINE</p></div><div class="os-counts">${counts.map(([label,n])=>`<div><strong>${n}</strong><span>${label}</span></div>`).join('')}</div><p class="build-status">Currently building: ${projects.filter(p=>p.status==='building').map(p=>esc(p.name)).join(' · ')}</p></section>`;
const hub=`<section class="section exp-hub" id="experiences"><div class="exp-hub-top"><div><span class="eyebrow">THE INTERACTIVE SIDE</span><h2>Don’t just browse.<br><em>Get curious.</em></h2></div><p>Follow the connections. Try a miniature product. Bring a problem and explore what we could build.</p></div><div class="exp-hub-grid"><button type="button" class="exp-hub-card" data-experience="universe"><small>01 / CONNECT THE DOTS</small><strong>Explore the universe ↗</strong><span>A map of projects, capabilities and the ideas they share.</span></button><button type="button" class="exp-hub-card" data-open-challenge><small>02 / BRING A PROBLEM</small><strong>Challenge DevMania ↗</strong><span>Turn a business problem into a proposed digital system.</span></button><button type="button" class="exp-hub-card" data-experience="mania"><small>03 / MEET YOUR GUIDE</small><strong>Meet MANIA ↗</strong><span>Find something Alain built, or a starting point for your own idea.</span></button></div><div class="exp-hub-links"><button type="button" class="exp-button" data-experience="dna">Analyze DevMania DNA</button><button type="button" class="exp-button" data-experience="timeline">Time machine</button><button type="button" class="exp-button" data-experience="surprise">Surprise me</button><button type="button" class="exp-button exp-classified" data-experience="classified">PROJECT ?? / CLASSIFIED</button></div></section>`;
const entry='<section class="section idea-entry"><div><span class="eyebrow">YOUR NEXT PRODUCT</span><h2>Have an idea?<br><em>Let’s give it shape.</em></h2><p>Explore the systems your product could need and discover related DevMania work.</p></div><button class="button" type="button" data-open-builder>Build my idea</button></section>';
let page=fs.readFileSync('src/index.template.html','utf8').replace('<!-- PROJECT_REGISTRY -->',work).replace('<!-- OS_STATUS -->',status).replace('<!-- IDEA_ENTRY -->',hub+entry);
fs.writeFileSync('dist/index.html',page);fs.copyFileSync('src/projects.json','dist/projects.json');
for(const file of ['os.js','os.css','matcher.js','builder.js','terminal.js','experience-state.js','experiences.js','experiences.css','playground.js','universe.js'])fs.copyFileSync('src/'+file,'dist/'+file);
console.log(`Built ${projects.length} project cards and interactive portfolio assets.`);
// Embed an explicit public-file allowlist in the Worker; no repository source is served.
const blogFiles=buildBlog();
const publicNames=['index.html','style.css','app.js','os.css','os.js','matcher.js','builder.js','terminal.js','projects.json','experience-state.js','experiences.js','experiences.css','playground.js','universe.js'];
const files=[...publicNames,...blogFiles,...fs.readdirSync('dist/assets').map(n=>'assets/'+n)];const assets={};
const types={xml:'application/xml; charset=utf-8',txt:'text/plain; charset=utf-8',html:'text/html; charset=utf-8',css:'text/css; charset=utf-8',js:'text/javascript; charset=utf-8',json:'application/json',png:'image/png',jpeg:'image/jpeg',jpg:'image/jpeg',svg:'image/svg+xml',webp:'image/webp'};
for(const name of files){const ext=name.split('.').pop();const binary=['png','jpeg','jpg','webp'].includes(ext);assets['/'+name]={type:types[ext]||'application/octet-stream',base64:binary,body:fs.readFileSync('dist/'+name,binary?'base64':'utf8')}}
fs.mkdirSync('dist/server',{recursive:true});fs.writeFileSync('dist/server/assets.js','export default '+JSON.stringify(assets)+';');fs.writeFileSync('dist/server/projects.js','export default '+JSON.stringify(projects)+';');fs.copyFileSync('server/worker.js','dist/server/index.js');
const validator=fs.readFileSync('src/builder.js','utf8').match(/export function validConcept[\s\S]*?\nexport function mountBuilder/)[0].replace(/\nexport function mountBuilder$/,'');fs.writeFileSync('dist/server/validation.js',validator);
fs.mkdirSync('dist/.openai',{recursive:true});fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');
