import {experienceState as state,pickSurprise} from './experience-state.js';

export function createExperiences(api) {
  const {el,modal,projects,track,record,contact,openBuilder,openTerminal,search,activateMania}=api;
  let active;
  const button=(text,action,style='exp-button')=>{const b=el('button',text,style);b.type='button';b.onclick=action;return b};
  function shell(title,wide=false){const s=modal(title);active=s;if(wide)s.dialog.classList.add('exp-wide');return s}
  function heading(c,kicker,title,copy){c.append(el('p',kicker,'exp-kicker'),el('h3',title,'exp-title'));if(copy)c.append(el('p',copy,'exp-intro'))}
  function enquiry(c,brief=''){const strip=el('div',undefined,'exp-enquiry');strip.append(el('p','What could we build for you?'),button('Start a project ↗',()=>contact(brief),'button'));c.append(strip)}
  function related(c,ps){const list=el('div',undefined,'exp-project-list');for(const p of ps){const b=button('',()=>project(p),'exp-project-item');b.append(el('span',p.name),el('small',p.status==='live'?'Published ↗':'In the build ↗'));list.append(b)}c.append(list)}
  function actions(c,p){const row=el('div',undefined,'exp-actions');if(p.experience?.xrayEnabled)row.append(button('X-Ray',()=>xray(p)));if(p.experience?.playground?.enabled)row.append(button('Try it',()=>playground(p)));if(p.experience?.buildStory?.enabled)row.append(button('Watch me build it',()=>story(p)));if(p.url){const a=el('a','Visit live project ↗','exp-button');a.href=p.url;a.target='_blank';a.rel='noopener noreferrer';row.append(a)}c.append(row)}
  function project(p,reason='') {record('project',p.id);const {content:c}=shell(p.name);heading(c,p.status==='live'?'PUBLISHED PROJECT':'IN THE BUILD',p.name,reason||p.shortDescription);if(p.image){const img=el('img',undefined,'exp-project-image');img.src=p.image;img.alt=p.imageAlt;img.loading='lazy';c.append(img)}if(reason)c.append(el('p',p.shortDescription));actions(c,p);enquiry(c,'I am interested in a project inspired by '+p.name+'.')}
  function xray(p){record('project',p.id);track('xray_opened',{projectId:p.id});const {content:c}=shell(p.name+' / X-Ray');heading(c,'PRODUCT X-RAY','Behind the experience.','Explore the public capabilities that shape this product.');if(p.status!=='live')c.append(el('p','In development: this map describes the planned product experience.','os-notice'));const map=el('ol',undefined,'exp-architecture');const nodes=p.experience?.publicArchitecture?.nodes||[];for(const [i,n] of nodes.entries()){const li=el('li');li.append(el('small',String(i+1).padStart(2,'0')),el('strong',n.label));map.append(li)}c.append(map,el('h3','Follow a capability'));const chips=el('div',undefined,'os-chips');for(const cap of p.capabilities)chips.append(button(cap,()=>universe(cap)));c.append(chips,button('Normal view',()=>project(p)));enquiry(c,'I would like to discuss systems like '+p.name+'.')}
  async function playground(p){record('project',p.id);const s=shell(p.name+' / Playground');s.content.append(el('p','Opening playground…'));try{const m=await import('./playground.js');if(s.dialog.open)m.mountPlayground(s,{...api,project:p,button,onProject:()=>project(p)})}catch{if(s.dialog.open)s.content.replaceChildren(el('p','The demo could not load. Your portfolio is still available.'),button('View project',()=>project(p)))}}
  async function universe(tag=''){track('universe_opened');if(tag)record('category',tag);const s=shell('DevMania Universe',true);s.content.append(el('p','Mapping public project relationships…'));try{const m=await import('./universe.js');if(s.dialog.open)m.mountUniverse(s,{...api,button,tag,onProject:project})}catch{if(s.dialog.open){s.content.replaceChildren(el('p','Explore the project list.'));related(s.content,projects)}}}
  function dna(){track('dna_opened');const {content:c}=shell('DevMania DNA');heading(c,'ANALYZE DEVMANIA DNA','Built. Not self-rated.','Every signal below is backed by projects in this portfolio. Counts include published work and clearly marked projects in development.');const groups=[['Web development',p=>p.platforms.includes('web')],['Mobile apps',p=>p.categories.includes('Apps')],['AI',p=>p.capabilities.includes('ai')],['Marketplaces',p=>p.capabilities.includes('marketplace')],['Booking systems',p=>p.capabilities.includes('booking')],['Logistics',p=>p.capabilities.includes('logistics')]];const grid=el('div',undefined,'exp-dna');const detail=el('div');detail.setAttribute('aria-live','polite');for(const [label,predicate] of groups){const ps=projects.filter(predicate);const b=button('',()=>{track('dna_capability_selected',{capability:label,resultCount:ps.length});record('category',label);detail.replaceChildren(el('h3',label+' / '+ps.length+' portfolio entries'));related(detail,ps)},'exp-dna-row');b.append(el('span',label),el('strong',String(ps.length).padStart(2,'0')),el('small','View evidence ↗'));grid.append(b)}c.append(grid,detail);enquiry(c)}
  function timeline(){track('timeline_opened');const {content:c}=shell('DevMania Time Machine');heading(c,'TIME MACHINE','Every build has a story.','Only verified dates belong on this timeline. Undated projects remain separate.');const date=p=>p.experience?.verifiedDate||p.launchDate;const dated=projects.filter(p=>/^\d{4}(-\d{2}(-\d{2})?)?$/.test(date(p)||'')).sort((a,b)=>date(a).localeCompare(date(b)));if(dated.length){const label=el('label','Scrub the timeline');const scrub=el('input');scrub.type='range';scrub.min=0;scrub.max=dated.length-1;scrub.value=0;const preview=el('div');const show=()=>{const p=dated[Number(scrub.value)];scrub.setAttribute('aria-valuetext',date(p)+' '+p.name);preview.replaceChildren(el('p',date(p),'exp-kicker'));related(preview,[p])};scrub.oninput=show;label.append(scrub);c.append(label,preview);show()}else c.append(el('p','Verified launch dates have not been added yet. Explore the collection below without an invented chronology.','os-notice'));const undated=projects.filter(p=>!dated.includes(p));if(undated.length){c.append(el('h3','Date not recorded'));related(c,undated)}heading(c,'NEXT PROJECT','Could be yours.');enquiry(c)}
  function story(p){track('build_story_started',{projectId:p.id});const {content:c,dialog}=shell(p.name+' / Build story');heading(c,'WATCH ME BUILD IT',p.name,'A 60-second conceptual story, not a recording of actual development.');if(p.status!=='live')c.append(el('p','This project is in development. This story illustrates its intended experience.','os-notice'));const steps=p.experience.buildStory.steps;let elapsed=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;const stage=el('div',undefined,'exp-story-stage');const time=el('p',undefined,'exp-kicker');const title=el('h3');const dots=el('div',undefined,'exp-story-dots');steps.forEach(()=>dots.append(el('span')));stage.append(time,title,dots);const progress=el('progress');progress.max=60;progress.setAttribute('aria-label','Conceptual build story progress');const pause=button(playing?'Pause':'Play',()=>{playing=!playing;pause.textContent=playing?'Pause':'Play'});const skip=button('Skip to next step',()=>{elapsed=steps.find(s=>s.timestamp>elapsed)?.timestamp??60;draw()});const restart=button('Restart',()=>{elapsed=0;playing=false;pause.textContent='Play';draw()});const draw=()=>{const index=steps.findLastIndex(s=>s.timestamp<=elapsed);time.textContent=(elapsed===60?'01:00':'00:'+String(elapsed).padStart(2,'0'))+' / 01:00';title.textContent=elapsed>=60?'Concept complete ✓':steps[Math.max(0,index)].label;[...dots.children].forEach((n,i)=>n.classList.toggle('active',i<=index));progress.value=elapsed;if(elapsed>=60){playing=false;pause.textContent='Play';pause.disabled=true}else pause.disabled=false};const timer=setInterval(()=>{if(playing&&!document.hidden){elapsed=Math.min(60,elapsed+1);draw()}},1000);dialog.addEventListener('close',()=>clearInterval(timer),{once:true});c.append(stage,progress,pause,skip,restart);draw();actions(c,p);enquiry(c)}
  function surprise(){track('surprise_me_used');const p=pickSurprise(projects);if(p)project(p,'Selected for you: '+p.name+' brings '+p.capabilities.slice(0,2).join(' and ')+' into one product experience.')}
  function classified(){track('classified_project_attempted');const {content:c}=shell('Classified / Project ??');const unlocked=state.terminalDiscovered&&state.viewedProjects.length>=3;if(unlocked){track('classified_project_unlocked');heading(c,'YOU FOUND IT.','Curiosity looks good on you.',"There isn’t actually a secret repository here. I wanted to see how curious you are. Since you’ve made it this far, let’s build something people want to explore like this.");enquiry(c)}else{heading(c,'ACCESS LEVEL INSUFFICIENT','PROJECT ??','Two clues. All inside this website.');const clues=el('ul');clues.append(el('li',(state.viewedProjects.length>=3?'✓ ':'○ ')+'Explore three different projects ('+Math.min(3,state.viewedProjects.length)+'/3).'),el('li',(state.terminalDiscovered?'✓ ':'○ ')+'Find Developer Mode in the footer.'));c.append(clues,button('Explore the universe',()=>universe()));}}
  function mania(){track('mania_opened');const {content:c}=shell('◉ MANIA');heading(c,'WEBSITE INTELLIGENCE',"Hey. I’m MANIA.",'Looking for something Alain built, or thinking about building something yourself?');if(state.viewedProjects.length)c.append(el('p',`You’ve explored ${state.viewedProjects.length} projects this session. Let’s connect the dots.`,'exp-session'));const grid=el('div',undefined,'exp-mania-grid');const choices=[['Explore projects','Find the work behind an idea.',search],['I have an idea','Turn your idea into a project brief.',()=>openBuilder()],['I have a problem','Challenge DevMania to propose a system.',()=>openBuilder('','challenge')],['Surprise me','Discover a project you might have missed.',surprise],['Explore the universe','Follow connections across the portfolio.',()=>universe()],['Analyze DNA','See capabilities backed by real work.',dna]];for(const [label,copy,action] of choices){const b=button('',()=>{track('mania_action_selected',{action:label});active?.dialog.close();action()},'exp-mania-card');b.append(el('strong',label),el('span',copy));grid.append(b)}c.append(grid);const tools=el('div',undefined,'exp-actions');tools.append(button('Time machine',timeline),button('Discover Mania Mode',()=>{active?.dialog.close();activateMania()}));c.append(tools)}
  return {project,xray,playground,universe,dna,timeline,story,surprise,classified,mania};
}
