import {recordExperience} from './experience-state.js';
import {searchProjects} from './matcher.js';
export const track=(event,metadata={})=>{const safe={};for(const key of ['productType','resultCount','command','source','projectId','demoType','capability','action','achievement'])if(metadata[key]!==undefined)safe[key]=metadata[key];if(Array.isArray(window.dataLayer))window.dataLayer.push({event,...safe});document.dispatchEvent(new CustomEvent('devmania:analytics',{detail:{event,...safe}}))};
export const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n};
export function modal(title){const previous=document.querySelector('dialog[open]');const returnFocus=previous?._returnFocus||document.activeElement;previous?.close();const d=el('dialog',undefined,'os-dialog');const top=el('div',undefined,'os-modal-head');const h=el('h2',title);h.id='modal-title-'+Math.random().toString(36).slice(2);d.setAttribute('aria-labelledby',h.id);const x=el('button','Close','os-close');x.type='button';x.onclick=()=>d.close();top.append(h,x);d.append(top);const content=el('div',undefined,'os-modal-content');d.append(content);d._returnFocus=returnFocus;d.addEventListener('close',()=>{d.remove();if(!document.querySelector('dialog[open]')&&returnFocus?.isConnected)returnFocus.focus()});document.body.append(d);d.showModal();return{dialog:d,content}}
let registry=[];let filterIds=null;let bootDone=false;
function boot(){let seen=true;try{seen=sessionStorage.getItem('devmaniaBootSeen')==='1';sessionStorage.setItem('devmaniaBootSeen','1')}catch{}if(seen||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const overlay=el('div',undefined,'os-boot');overlay.setAttribute('role','status');const label=el('strong','DEV//MANIA');const lines=el('pre','INITIALIZING...');const skip=el('button','Skip introduction','os-close');overlay.append(label,lines,skip);document.body.append(overlay);
 const steps=['Loading projects............. ✓','Loading mobile apps.......... ✓','Loading experiments.......... ✓','Loading questionable ideas... ✓','SYSTEM READY.\nWELCOME TO DEVMANIA.'];let i=0;
 const finish=(skipped=false)=>{if(bootDone)return;bootDone=true;clearInterval(t);clearTimeout(end);overlay.remove();document.removeEventListener('keydown',key);track(skipped?'devmania_boot_skipped':'devmania_boot_completed')};const key=()=>finish(true);document.addEventListener('keydown',key);overlay.onclick=()=>finish(true);const t=setInterval(()=>{if(i<steps.length)lines.textContent+='\n'+steps[i++]},330);const end=setTimeout(()=>finish(),2200);
}
boot();
export function focusProject(p){record('project',p.id);document.querySelector('.os-dialog')?.close();resetFilter();const card=document.getElementById('project-'+p.id);if(card){card.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});card.setAttribute('tabindex','-1');card.focus({preventScroll:true});card.classList.add('project-highlight');setTimeout(()=>card.classList.remove('project-highlight'),2200)}}
export function contact(brief='',type=''){document.querySelector('.os-dialog')?.close();const form=document.getElementById('brief-form');if(brief)form.elements.idea.value=brief;const select=form.elements.type;if(type){const option=[...select.options].find(o=>o.textContent.toLowerCase().includes(type.toLowerCase()));if(option)select.value=option.value}form.scrollIntoView({behavior:'smooth',block:'center'});form.elements.idea.focus({preventScroll:true});track('contact_started',{source:'interactive'})}
let filterBanner;
function resetFilter(){filterIds=null;document.querySelectorAll('.work-card').forEach(c=>{c.hidden=false;if(c.parentElement.classList.contains('exp-project-wrap'))c.parentElement.hidden=false;c.classList.remove('project-highlight')});document.querySelectorAll('.work-status-group,.work-category').forEach(c=>c.hidden=false);if(filterBanner)filterBanner.hidden=true}
function filterProjects(ps){filterIds=new Set(ps.map(p=>p.id));document.querySelectorAll('.work-card').forEach(c=>{c.hidden=!filterIds.has(c.dataset.projectId);if(c.parentElement.classList.contains('exp-project-wrap'))c.parentElement.hidden=c.hidden});document.querySelectorAll('.work-status-group').forEach(c=>c.hidden=![...c.querySelectorAll('.work-card')].some(n=>!n.hidden));document.querySelectorAll('.work-category').forEach(c=>c.hidden=![...c.querySelectorAll('.work-card')].some(n=>!n.hidden));filterBanner.hidden=false;filterBanner.querySelector('span').textContent=`Showing ${ps.length} matching project${ps.length===1?'':'s'}.`;track('project_filter_applied',{resultCount:ps.length});document.getElementById('work').scrollIntoView({behavior:'smooth'})}
export async function openBuilder(initial='',mode='idea'){const challenge=mode==='challenge';track(challenge?'challenge_started':'idea_builder_started');if(!challenge)record('idea-start');const shell=modal(challenge?'Challenge DevMania':'Build my idea');shell.content.textContent='Opening your workspace…';try{const mod=await import('./builder.js');if(shell.dialog.open)mod.mountBuilder(shell,{projects:registry,initial,mode,contact,focusProject:p=>launchExperience('project',p),track,el,record})}catch{shell.content.replaceChildren(el('p','This experience could not load. You can still send your brief directly.'));const b=el('button','Continue to enquiry','button');b.onclick=()=>contact(initial);shell.content.append(b)}}
async function openTerminal(){record('terminal');track('terminal_opened');const shell=modal('Developer terminal');shell.dialog.classList.add('terminal-dialog');shell.content.textContent='Opening terminal…';try{const mod=await import('./terminal.js');if(shell.dialog.open)mod.mountTerminal(shell,{projects:registry,contact,focusProject:p=>launchExperience('project',p),track,el})}catch{shell.content.textContent='Terminal unavailable. Close this panel to continue browsing.'}}
function palette(){track('command_palette_opened');const {dialog,content}=modal('Ask DevMania');const form=el('form');const label=el('label','Find a project or describe what you want to build');const input=el('input');input.type='search';input.placeholder='Try “show me booking platforms”';input.maxLength=500;label.append(input);const submit=el('button','Search','button');form.append(label,submit);const suggestions=el('div',undefined,'os-chips');['Mobile apps','Logistics','AI projects','Booking platforms','Newest projects'].forEach(q=>{const b=el('button',q);b.type='button';b.onclick=()=>{input.value=q;render()};suggestions.append(b)});const response=el('div');response.setAttribute('aria-live','polite');content.append(form,suggestions,response);
 function render(){track('command_submitted');const q=input.value;const result=searchProjects(q,registry);response.replaceChildren(el('p',result.message));const list=el('div',undefined,'os-results');result.projects.forEach(p=>{const b=el('button',undefined,'os-result');b.type='button';b.append(el('strong',p.name),el('span',`${p.categories[0]} · ${p.status==='live'?'Published':'In the Build'} · ${p.capabilities.join(', ')}`));b.onclick=()=>{track('project_opened_from_command');focusProject(p)};list.append(b)});response.append(list);if(result.projects.length){const apply=el('button','Show matching projects','button');apply.onclick=()=>{dialog.close();filterProjects(result.projects)};response.append(apply)}else{const build=el('button','Build my idea','button');build.onclick=()=>{dialog.close();openBuilder(q)};response.append(build)}const clear=el('button','Clear / Reset','os-close');clear.onclick=()=>{resetFilter();input.value='';response.replaceChildren();input.focus()};response.append(clear)}
 form.onsubmit=e=>{e.preventDefault();render()};input.focus();
}
fetch('projects.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(projects=>{registry=projects;filterBanner=el('div',undefined,'os-filter-banner');filterBanner.hidden=true;const reset=el('button','Reset portfolio','os-close');reset.onclick=resetFilter;filterBanner.append(el('span'),reset);document.getElementById('work').prepend(filterBanner);
 const dock=el('button',undefined,'os-command-dock');dock.type='button';dock.setAttribute('aria-haspopup','dialog');dock.append(el('span','◉'),el('span','MANIA · Explore. Imagine. Build.'),el('kbd','Ctrl / ⌘ K'));dock.onclick=()=>launchExperience('mania');document.body.append(dock);
 document.querySelectorAll('[data-open-builder]').forEach(b=>b.onclick=()=>openBuilder());document.querySelectorAll('[data-open-terminal]').forEach(b=>b.onclick=openTerminal);
 wireExperiences();
 document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();launchExperience('mania')}});
}).catch(()=>{document.querySelectorAll('[data-open-builder]').forEach(b=>b.onclick=()=>contact());document.querySelectorAll('[data-open-terminal]').forEach(b=>b.hidden=true)});
const sequence=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'];let position=0,maniaTimer,maniaNote;
function stopMania(){clearTimeout(maniaTimer);document.body.classList.remove('mania-mode');maniaNote?.remove()}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){stopMania();return}if(e.target.closest('input,textarea,select,[contenteditable]'))return;const key=e.key.length===1?e.key.toLowerCase():e.key;position=key===sequence[position]?position+1:key===sequence[0]?1:0;if(position===sequence.length){position=0;activateMania()}});
document.getElementById('brief-form').addEventListener('submit',()=>track('contact_started',{source:'form'}));

let experiencesPromise,lastToast=-Infinity;
function record(event,value){for(const achievement of recordExperience(event,value)){track('achievement_unlocked',{achievement});if(Date.now()-lastToast<15000)continue;lastToast=Date.now();const toast=el('div',undefined,'exp-achievement');toast.setAttribute('role','status');toast.append(el('strong',achievement),el('span','A little curiosity goes a long way.'));document.body.append(toast);setTimeout(()=>toast.remove(),3500)}}
function activateMania(){stopMania();record('mania');document.body.classList.add('mania-mode');maniaNote=el('div','MANIA MODE ACTIVATED · Escape to exit','mania-note');maniaNote.setAttribute('role','status');document.body.append(maniaNote);track('mania_mode_activated');maniaTimer=setTimeout(stopMania,5500)}
async function launchExperience(name,arg){try{experiencesPromise??=import('./experiences.js').then(m=>m.createExperiences({el,modal,projects:registry,track,record,contact,openBuilder,openTerminal,search:palette,activateMania}));const experiences=await experiencesPromise;experiences[name]?.(arg)}catch{experiencesPromise=null;const {content}=modal('Explore DevMania');content.append(el('p','This experience could not load. You can still browse the portfolio or start an enquiry.'));const b=el('button','Explore projects','button');b.onclick=()=>{document.querySelector('dialog[open]')?.close();document.getElementById('work').scrollIntoView()};content.append(b)}}
function wireExperiences(){document.querySelectorAll('[data-experience]').forEach(b=>b.onclick=()=>launchExperience(b.dataset.experience));document.querySelectorAll('[data-open-challenge]').forEach(b=>b.onclick=()=>openBuilder('','challenge'));document.querySelectorAll('[data-project-action]').forEach(b=>b.onclick=()=>{const p=registry.find(p=>p.id===b.dataset.project);if(p)launchExperience(b.dataset.projectAction,p)});document.querySelectorAll('.work-card').forEach(c=>c.addEventListener('click',()=>record('project',c.dataset.projectId)));}
