export function mountPlayground({content:c},{el,project:p,button,track,contact,onProject}) {
  track('playground_started',{projectId:p.id,demoType:p.experience.playground.demoType});
  const type=p.experience.playground.demoType;let complete=false;
  c.replaceChildren(el('p','INTERACTIVE PLAYGROUND','exp-kicker'),el('h3',p.name,'exp-title'),el('p','Simulation only. Sample data. No real bookings, payments or production records.','os-notice'));
  const area=el('div',undefined,'exp-demo');c.append(area);
  const field=(form,label,type='text')=>{const l=el('label',label);const input=el('input');input.type=type;input.required=true;l.append(input);form.append(l);return input};
  const select=(form,label,values)=>{const l=el('label',label);const s=el('select');for(const v of values){const o=el('option',v);o.value=v;s.append(o)}l.append(s);form.append(l);return s};
  const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
  const finish=()=>{if(!complete){complete=true;track('playground_completed',{projectId:p.id,demoType:type})}area.append(el('p','Like this workflow? Let’s shape one for your business.'),button('Build something like this',()=>contact('I would like to discuss a product with a workflow like the '+p.name+' demo.'),'button'),button('Try again',()=>{complete=false;render()}))};
  function tracking(){const form=el('form');const code=field(form,'Sample tracking number');code.value='DEMO-TRACK-001';code.maxLength=30;const error=el('p');error.setAttribute('role','status');const submit=el('button','Track sample shipment','button');form.append(submit,error);area.append(el('p','Follow a sample shipment from dispatch to delivery. Use DEMO-TRACK-001.'),form);form.onsubmit=e=>{e.preventDefault();if(code.value.trim().toUpperCase()!=='DEMO-TRACK-001'){error.textContent='This demo recognizes only DEMO-TRACK-001. No real carrier lookup is made.';return}area.replaceChildren(el('p','DEMO-TRACK-001 · SAMPLE JOURNEY','exp-kicker'));const list=el('ol',undefined,'exp-journey');const steps=['Shipment created','Collected by carrier','In transit','Out for delivery','Delivered'];let current=0;const status=el('p');status.setAttribute('role','status');const next=button('Advance shipment',()=>{current++;draw()});const draw=()=>{list.replaceChildren();steps.forEach((s,i)=>{const li=el('li',s,i<=current?'reached':'');if(i===current)li.setAttribute('aria-current','step');list.append(li)});status.textContent=steps[current];next.disabled=current===steps.length-1;if(next.disabled){next.remove();finish()}};area.append(list,status,next);draw()}}
  function padel(){const form=el('form');const date=field(form,'Sample booking date','date');date.min=today();date.value=today();select(form,'Sample court',['Demo Court A','Demo Court B']);const slots=select(form,'Sample time',['17:00 – 18:00','18:00 – 19:00','19:00 – 20:00']);const submit=el('button','Review sample booking','button');form.append(submit);area.append(el('p','Choose a sample court and time. These slots do not represent actual availability.'),form);form.onsubmit=e=>{e.preventDefault();const chosenDate=date.value, court=form.querySelector('select').value,slot=slots.value;area.replaceChildren(el('p','REVIEW YOUR DEMO BOOKING','exp-kicker'),el('h3',court),el('p',chosenDate+' · '+slot),button('Simulate confirmation',()=>{area.replaceChildren(el('p','SIMULATION COMPLETE ✓','exp-kicker'),el('h3','Your sample court is selected.'),el('p',court+' · '+chosenDate+' · '+slot),el('p','No reservation was created. Contact the venue for real availability.'));finish()},'button'),button('Change selection',render))}}
  function stay(){const form=el('form');const start=field(form,'Sample check-in','date');start.min=today();start.value=today();const end=field(form,'Sample check-out','date');end.min=today();const guests=select(form,'Guests',['1 guest','2 guests','3 guests','4 guests']);const bungalow=select(form,'Sample accommodation',['Demo Pine Bungalow','Demo Valley Bungalow']);const error=el('p');error.setAttribute('role','status');const submit=el('button','Review sample stay','button');form.append(submit,error);area.append(el('p','Explore a sample reservation flow. Accommodation names and availability are illustrative.'),form);form.onsubmit=e=>{e.preventDefault();const nights=(Date.parse(end.value)-Date.parse(start.value))/86400000;if(!Number.isFinite(nights)||nights<=0){error.textContent='Choose a check-out date after check-in.';return}const text=`${bungalow.value} · ${guests.value} · ${nights} night${nights===1?'':'s'} · ${start.value} to ${end.value}`;area.replaceChildren(el('p','YOUR SAMPLE STAY','exp-kicker'),el('h3',bungalow.value),el('p',text),button('Simulate reservation',()=>{area.replaceChildren(el('p','SIMULATION COMPLETE ✓','exp-kicker'),el('h3','A getaway, mapped out.'),el('p',text),el('p','No booking or payment was made. This is a product demonstration.'));finish()},'button'),button('Change dates',render))}}
  function render(){area.replaceChildren();if(type==='tracking')tracking();else if(type==='padel')padel();else stay()}
  render();c.append(button('Back to project',onProject));
}
